### ISSUE TITLE
Development environment setup guide should suggest `requirements-docs.txt`

### ISSUE THREAD

**Issue by zevisert** [unionai-oss/unionml#146]
Pre-commit currently requires the dependencies from `requirements-docs.txt`. The contributors guide at https://unionml.readthedocs.io/en/latest/contributing_guide.html#development-environment-setup suggests to install only `requirements-dev.txt`. Used pyenv to make my venv, but there's nothing special about that.

```console
> pyenv install 3.7.13
[...]
> pyenv virtualenv 3.7.13 unionml 
[...]
> pyenv local unionml
[...]
> pip install -r requirements-dev.txt
[...]
> pre-commit install
[...]
> pre-commit run --all
flake8...................................................................Passed
black....................................................................Passed
isort....................................................................Passed
check yaml...............................................................Passed
fix end of files.........................................................Passed
trim trailing whitespace.................................................Passed
shellcheck...........................................(no files to check)Skipped
mypy.....................................................................Passed
convert myst markdown to jupyter notebooks...............................Failed
- hook id: convert-myst-to-ipynb
- exit code: 1

Traceback (most recent call last):
  File "/opt/tooling/pyenv/versions/3.7.13/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/opt/tooling/pyenv/versions/3.7.13/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/code/oss/github/unionai-oss/unionml/scripts/myst_to_ipynb.py", line 14, in <module>
    import jupytext
ModuleNotFoundError: No module named 'jupytext'

```

**Comment by Smartmind12** [comment]
@zevisert Can you assign this issue to me so that i can work on it?

**Comment by zevisert** [comment]
@Smartmind12 I don't have permission to do that in this repo, but there's an action you can take to do it yourself. Leave a comment like this https://github.com/unionai-oss/unionml/issues/56#issuecomment-1176435287 to assign it to yourself

**Comment by Smartmind12** [comment]
#self-assign
